source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!

def pods
    pod 'Applepie', '~> 0.0.2'
    pod 'Apollo', '~> 0.9.4'
end

target 'graphql' do
    pods
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == 'ReactiveCocoa'
        config.build_settings['SWIFT_VERSION'] = '4'
        else
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
